### ISSUE TITLE
JStorage Max Allowed Size in browsers

### ISSUE THREAD

**Issue by sandipray63in** [andris9/jStorage#105]
What is the max allowed size of JStorgae in different browsers(including mobile browsers)? I want to know this since I want to calculate the minimum of all the max allowed sizes and based on that I want to store some number of objects so that it can be used without any issue across most(almost any) browser(be it desktop or laptop or tablet or mobile based).

Regards,
Sandip

**Comment by andris9** [comment]
If you keep your data under 1MB then it should be relatively safe. You can store more than that but it is not advisable for several reasons (synchronous read/write, domain bound shared storage, utf-16 eats up half the bytes, JSON overhead etc.). If you need to store very complex data or more than small objects (>100kB) then consider using IndexedDB instead.

**Comment by sandipray63in** [comment]
Got it. Thanks @andris9.
