### ISSUE TITLE
$.jStorage.get(key) returns null after manual page reload in firefox 3.6 (using jQuery 1.4.2)

### ISSUE THREAD

**Issue by marcora** [andris9/jStorage#8]

**Comment by bimacknyas** [comment]
Any one check jstorage in IE7 ??? It is not working. Any one having solution please reply.

**Comment by cYbercOsmOnauT** [comment]
Sorry but who really cares about such an old browser? ;)

Am 10.02.2015 um 09:01 schrieb Manas Ranjan Pradhan:

**Comment by doublejosh** [comment]
"Who cares" is not a useful response. Plenty of the world is on less modern technology.

**Comment by cYbercOsmOnauT** [comment]
Okay.. lets do it the supporter way. Any error messages that can be provided? Debugging IE is mostly hell.

**Comment by andris9** [comment]
IE7 requires additional library for using JSON, the example at jStorage homepage uses [JSON2](http://cdnjs.cloudflare.com/ajax/libs/json2/20110223/json2.js) but other options apply as well (including Prototypejs, or MooTools or jQuery-JSON that also provide the same functionality). Anyway I do not think there's anything broken with jStorage on IE7 but to see what is wrong you should check the error messages as suggested by @cYbercOsmOnauT and also see that JSON is available for jStorage to use.
