### ISSUE TITLE
Handle race conditions correctly

### ISSUE THREAD

**Issue by qbolec** [andris9/jStorage#92]
Not even sure if the problem is in race conditions, since it involves just a single tab open.
I used following code:
```
<!doctype html>
<script src="//cdnjs.cloudflare.com/ajax/libs/json2/20110223/json2.js"></script>
<script src="jstorage.js"></script>
<script>
  var me = "Client"+Math.random();
  var received = 0;
  $.jStorage.subscribe("aaa",function(chanel,data){
    received++;
    console.log("received message no. " + data[0] + " from client " + data[1] + " so far received "+ received + " messages");
  });
  for(var i=0;i<1000;++i){
    $.jStorage.publish("aaa",[i,me]);
  }
</script>
```
I'd expect it to report 1000 received messages, but actually only around ~800 pass trough in 
`"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"`
It looks like the missing messages are the initial ones.

**Comment by qbolec** [comment]
I'd bet that the problem is with _dropOldEvents() which eats events older than 2s.

**Comment by andris9** [comment]
This behavior is unfortunately intentional, the pub/sub interface is only suitable for low throughput.
