### ISSUE TITLE
Use jStorage inside Web Worker?

### ISSUE THREAD

**Issue by shahafabileah** [andris9/jStorage#94]
I have a web page that needs to operate on a bunch of data.  As soon as the page loads, I kick off an ajax request.  When the results come back, I put them all in jStorage for later use.

This pattern is OK, except that all this fetching activity sometimes causes the UI to lock up.

I'm thinking about moving this code into a Web Worker, as suggested here (among other places):
https://developers.google.com/web/fundamentals/performance/rendering/optimize-javascript-execution?hl=en

The trouble is that jStorage relies on jQuery, and jQuery doesn't work in Web Workers (because it's built for DOM manipulations, and you can't touch the DOM from a Web Worker).

It looks like there are other flavors of jQuery that skip that DOM-manipulation code and that should work inside a Web Worker: https://github.com/kpozin/jquery-nodom

So, I wonder, is it a good idea to try to use jStorage with jQuery-lite in a Web Worker?  Will the data I set() inside the Web Worker be available in the main thread?  And does this pattern actually save work, or will I inadvertently cause a bunch of other work due to storage-changed events firing?

**Comment by andris9** [comment]
jQuery is only needed by jStorage in IE6 and IE7. jStorage relies on localStorage to store its data but this isn't available in the WebWorker. I think you need to handle the actual data store in the main thread and use postMessage to communicate the data from main thread to workers and back.
