### ISSUE TITLE
can we have application prefix for the keys/ main key (jStorage)

### ISSUE THREAD

**Issue by murliatdure** [andris9/jStorage#95]
Even on multiple applications on the same domain/dev env gets clashed.
Thanks,

**Comment by doublejosh** [comment]
Great point, but you could just add a namespace prefix variable in your application that's set per environment.

Always a good idea to alway filter for your namespace when using $jStorage.index() anyhow so you can do more with localStage later.

**Comment by andris9** [comment]
The API of jStorage is more or less frozen by now but you could use prefixed keys to achieve the same thing, eg. like this:

    $.jStorage.set('myprefix:key', 'value');

**Comment by doublejosh** [comment]
Well it's easy enough to add a new optional param, so frozen API isn't a valid excuse ;)

On that subject @murliatdure, you could extend the function yourself...

```javascript
var $.jStorage.setStash;
$.jStorage.set = function set(label, val, prefix) {
  $.jStorage.setStash(prefix + label, val);
}
```

**Comment by doublejosh** [comment]
Whoop...
`var $.jStorage.setStash = var $.jStorage.set;`

**Comment by andris9** [comment]
Yeah, I guess the frozen api excuse is not a really good one as changes do happen from time to time. Nevertheless I'm not in favor of supporting namespaces, this would mean there would also be a need to list used namespaces, a way to index and flush data based on namespaces etc. it is not just using prefixes.

**Comment by doublejosh** [comment]
Sure, it's a can of worms.  Perhaps best left to another library leveraging such backends as jStorage.  Major tangent here, but something like this...

```javascript
$.storageSpace = {

  set: function set(label, val, prefix) {
    if (prefix) {
      label = prefix + label;
    }
    $.jStorage.set(label, va);
  },

  flush: function flush(prefix) {
    var index = $.jStorage.index();
    for (i in index) {
      if (index.hasOwnProperty(i) && index[i].indexOf(prefix) !== -1) {
        $.jStorage.deleteKey(index[i]);
      };
    }
  }

  index: function index(prefix) {
    var index = $.jStorage.index(),
        items = [];
    for (i in index) {
      if (index.hasOwnProperty(i) && index[i].indexOf(prefix) !== -1) {
        items.push($.jStorage.get(index[i]));
      };
    }
  }

};
```
Might be nicer to use an object constructor style syntax.
```javascript
var myStorage = new $.storageSpace('myNamespace');
myStorage.set('thing', {stuff: 'woot'});
myStorage.get('thing');
```
